### ISSUE TITLE
Archethic's token standard

### ISSUE THREAD

**Issue by samuel-uniris** [archethic-foundation/aeip#1]
We need to create the AEIP relative to the Archethic token standard to describe the goals, and the way it's managed by the network.

So the standard will define:
- [x] What Archethic tokens are (NFT, ERC20 like)
- [x] How to create them and use them
- [x] Format standardisation

**Comment by samuel-uniris** [comment]
The PR is merged and now open to review

**Comment by samuel-uniris** [comment]
@nilesh-uniris @Neylix @redDwarf03 @internet-zero @seb-uniris

**Comment by Neylix** [comment]
Hi ! Here some suggestions: 

## Difference between token and NFT
Actually there are two main type of token : fungible token (token) and non fungible token (NFT). Many application can handle both types, but their use case are completely different.
So I think we have to provide a way for applications to easily identify the type of a token. We can add the `type` of token in the content : 
```json
{
  "supply": 10,
  "type": "token",
  "name": "NAME OF MY TOKEN",
  "properties": [
    ...
  ]
}
```
The `type` value can be `token` or `nft`

## Defining what is a property
I think we should explain what is a property and how ot works.
Properties attributes is an array of property. Each property is composed by two attributes: `name` and `value`.
`name` is the name of the property to help application to find the good value they need
`value` is the value of the property

**Direct properties inside the properties array are applied to all token or nft**

The advantage to set an array of properties is that we can easily add new attribute to a property (for example we can add an attribute `type` to a property).

Here an example of properties : 
```json
{
  "supply": 2,
  "type": "nft",
  "name": "Sword",
  "properties": [
    {
      "name": "image",
      "value": "BASE64 OF THE IMAGE"
    },
    {
      "name": "attak damage",
      "value": 40
    }
  ]
}
```
## Defining mutiple collection of NFT
There are some use cases with NFT when we want to create NFTs with different properties but with some common properties. This can be called "collection".
With the new `type` of a token we can know of it is an NFT and then add specific control for it.
So we can add a specific property for NFT collection which will result of different NFT with their own id (as actually descibed in the AEIP2)

The collection property will result in an array of properties array : 
```json
{
  "properties": [
    {
      "name": "collection",
      "value": [
        [
          {
            "name": "image",
            "value": "link of the 1st NFT image"
          },
          {...}
        ],
        [
          {
            "name": "image",
            "value": "link of the 2st NFT image"
          }
        ]
      ]
    },
    {...}
  ]
}
```

So during validation the created NFTs will get the common properties (direct properties under properties array) and specific properties (specified in collection property according to the NFT id)

**If the collection properties is specified, the number of token to create (`supply`) need to have the same value as the size of the array of collection value (`supply == properties.find('collection').value.length`**

**The specification of this collection property works only for token of type `nft`. If token type is `token`, collection property can be anything else**

**For nft token, the property collection cannot be used in an other way as described before**

## Explaining NFT id
In some case, developper may want to specify the NFT id for adding specific value to a specific NFT id.
We can let them add a property `id` in the collection property array.
So we can have to case for creating NFT id : 
- If a `collection` property is set without id property, NFT id will be a counter starting from 0 to n. 0 is the first element in collection property, 1 is the second element ...
- If a `collection` property is set with id property, then the id will be the one defined in property

Example: 
Without id
```json
{
  "supply": 2,
  "type": "nft",
  "name": "NAME OF MY TOKEN",
  "properties": [
    {
      "name": "collection",
      "value": [
        [
          {...}
        ],
        [
          {...}
        ]
      ]
    }
  ]
}
```
will result in 
```json
[
  { "type": "TOKEN", "address": "address of the transaction", "id": 0 }
  { "type": "TOKEN", "address": "address of the transaction", "id": 1 }
]
```
With id
```json
{
  "supply": 2,
  "type": "nft",
  "name": "NAME OF MY TOKEN",
  "properties": [
    {
      "name": "collection",
      "value": [
        [
          {
            "name": "id",
            "value": 42
          }
        ],
        [
          {
            "name": "id",
            "value": 2022
          }
        ]
      ]
    }
  ]
}
```
Will result  in 
```json
[
  { "type": "TOKEN", "address": "address of the transaction", "id": 42 }
  { "type": "TOKEN", "address": "address of the transaction", "id": 2022 }
]
```

**If one property of the collection property has a specified id, then all the collection properties have to specify an id**

**The specification of this id property works only for token of type nft. If token type is token, id property can be anything else**

**For nft token, the property id inside the collection property cannot be used in an other way as described before**

**Comment by samuel-uniris** [comment]
Thanks @Neylix for your comments.
There are really relevant.

I'm wondering if we should specify the type "token|nft" or "fungible|non-fungible", as "token" might to broad in the meaning.

**Comment by samuel-uniris** [comment]
Another comment is regarding the collection attributes, the advantage to use list of list instead of list of objects, it's we can avoid the `collection` property specification: the size of the list determines the usage of a collection or not.

**Comment by samuel-uniris** [comment]
Updated at 76a63c532f165dc93fefdac66786016c06cf4d58

**Comment by apoorv-2204** [comment]
```
{  
content: 
   {  
       supply: <non-neg-integer()>,
       name: "<name-of-token>",
            # fungible, non-ft, multi token standard
            # fractional, smart nft(nft tied to physical asset)
        type: <FT,NFT,MT,FNT,SNFT>, 
            # when type is FT
        properties: nil,
                  # when type is nft
                  properties: 
                  {
                       collection-name: "" ,
                     info: ""
                    tokens: {
                        #id => props
                       0: {  name: 'red' , prop_url: "asdc.com||hash"},
                       1: {  name: 'purple', prop_url: ""  }, 
                       .
                       .
                       255: { name: 'white',  prop_url: 'storageptr'|| hash based addressing  }
                     }
                  }
                   # when type is MT
                  properties: 
                  {}
                  # when type is fractional nft
                  properties: 
                  {}
                  # when type SNFT , physically tied assets
                  properties: 
                  {}

       ]

   }
}
```
