### ISSUE TITLE
AEIP-2. Comments on Properties

### ISSUE THREAD

**Issue by pvalette** [archethic-foundation/aeip#9]
### Is your feature request related to a problem?

I am sorry I have other concerns about the Properties, hope that will help to progress.
 
- Seems that there are 2 roles in properties; 
one is to define some metadata of the token (parent) and to define a list of NFT instances (children). It will be nicer to separate these 2 items in different attributes, on an object and another one a collection.
  metadata:{}  &  instances: [].  (didn't find a better word than instances)

- Metadata are defined by an item with 2 attributes key/value, as JSON is based on "key:value", it is more efficient (size, implementation to find the value etc..) to use the native approach. example:
   [
      {  "key": "origin", "value": "France"},
      {  "key": "organism", "value": "DG" }
    ]
   should be
   {
        "origin": "France",
        "organism": "DG
    }

- For NFT instance, the id should be mandatory and controlled by the developer, I will not recommended to have the index based on the position in a collection (mix representation & business)

**Comment by samuel-uniris** [comment]
Hello @pvalette 
Thanks for the contribution.

I think the first one is interesting, we thought about it, before. 
The "key"/"value", was to make the schema evolutionary and still be validated.
But this can be implemented. 

For the second, I don't think should be mandatory, in some other blockchains it's either mandatory or self-defined in the contract (auto or specified). In the AEIP2 there is a mention to give the id in the property field.

**Comment by samuelmanzanera** [comment]
Closed by #14
